/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UrbanDeRouteImport } from './routes/urban-de'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as NewRoyalServicesRouteImport } from './routes/new-royal-services'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AishwaryaRentalRouteImport } from './routes/aishwarya-rental'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const UrbanDeRoute = UrbanDeRouteImport.update({
  id: '/urban-de',
  path: '/urban-de',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoyalServicesRoute = NewRoyalServicesRouteImport.update({
  id: '/new-royal-services',
  path: '/new-royal-services',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AishwaryaRentalRoute = AishwaryaRentalRouteImport.update({
  id: '/aishwarya-rental',
  path: '/aishwarya-rental',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/aishwarya-rental': typeof AishwaryaRentalRoute
  '/contact': typeof ContactRoute
  '/new-royal-services': typeof NewRoyalServicesRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/urban-de': typeof UrbanDeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/aishwarya-rental': typeof AishwaryaRentalRoute
  '/contact': typeof ContactRoute
  '/new-royal-services': typeof NewRoyalServicesRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/urban-de': typeof UrbanDeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/aishwarya-rental': typeof AishwaryaRentalRoute
  '/contact': typeof ContactRoute
  '/new-royal-services': typeof NewRoyalServicesRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/urban-de': typeof UrbanDeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/aishwarya-rental'
    | '/contact'
    | '/new-royal-services'
    | '/services'
    | '/sitemap.xml'
    | '/urban-de'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/aishwarya-rental'
    | '/contact'
    | '/new-royal-services'
    | '/services'
    | '/sitemap.xml'
    | '/urban-de'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/aishwarya-rental'
    | '/contact'
    | '/new-royal-services'
    | '/services'
    | '/sitemap.xml'
    | '/urban-de'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AishwaryaRentalRoute: typeof AishwaryaRentalRoute
  ContactRoute: typeof ContactRoute
  NewRoyalServicesRoute: typeof NewRoyalServicesRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UrbanDeRoute: typeof UrbanDeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/urban-de': {
      id: '/urban-de'
      path: '/urban-de'
      fullPath: '/urban-de'
      preLoaderRoute: typeof UrbanDeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-royal-services': {
      id: '/new-royal-services'
      path: '/new-royal-services'
      fullPath: '/new-royal-services'
      preLoaderRoute: typeof NewRoyalServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aishwarya-rental': {
      id: '/aishwarya-rental'
      path: '/aishwarya-rental'
      fullPath: '/aishwarya-rental'
      preLoaderRoute: typeof AishwaryaRentalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AishwaryaRentalRoute: AishwaryaRentalRoute,
  ContactRoute: ContactRoute,
  NewRoyalServicesRoute: NewRoyalServicesRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UrbanDeRoute: UrbanDeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
